<?php
/**
 * The theme settings — everything meant to be changeable without an editor.
 *
 * Why the Customizer and not a settings page of its own: it shows the effect
 * in the preview straight away, WordPress supplies saving, resetting and
 * capability checks, and the values land in theme mods — in the theme, not in
 * foreign tables. A theme you can get rid of again without database access is
 * the same attitude as the programs themselves.
 *
 * Every per-language field is generated by looping over suvantra_languages().
 * A third language brings its own fields; nothing has to be done here.
 *
 * @package Suvantra
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/* --------------------------------------------------------------- Sanitizing */

/**
 * Free text with a small set of markup — a footer needs no more, and allowing
 * more would mean permitting a <script> in the foot of every single page.
 *
 * @param string $value Raw value.
 * @return string
 */
function suvantra_sanitize_html( $value ) {
	return wp_kses( (string) $value, array(
		'a'      => array( 'href' => array(), 'title' => array(), 'rel' => array(), 'target' => array() ),
		'strong' => array(),
		'em'     => array(),
		'br'     => array(),
		'span'   => array(),
	) );
}

/**
 * @param string $value Raw value.
 * @return string
 */
function suvantra_sanitize_email( $value ) {
	$value = sanitize_email( (string) $value );
	return is_email( $value ) ? $value : '';
}

/**
 * @param mixed $value Raw value.
 * @return bool
 */
function suvantra_sanitize_checkbox( $value ) {
	return (bool) $value;
}

/**
 * A number forced into its bounds — no 3000 pixel measure.
 *
 * @param mixed                $value   Raw value.
 * @param WP_Customize_Setting $setting The setting.
 * @return int
 */
function suvantra_sanitize_number( $value, $setting ) {
	$control = $setting->manager->get_control( $setting->id );
	$min     = ( $control && isset( $control->input_attrs['min'] ) ) ? (int) $control->input_attrs['min'] : 0;
	$max     = ( $control && isset( $control->input_attrs['max'] ) ) ? (int) $control->input_attrs['max'] : 9999;
	return max( $min, min( $max, (int) $value ) );
}

/**
 * Only values that actually exist in the choice list.
 *
 * @param mixed                $value   Raw value.
 * @param WP_Customize_Setting $setting The setting.
 * @return string
 */
function suvantra_sanitize_choice( $value, $setting ) {
	$control = $setting->manager->get_control( $setting->id );
	$choices = ( $control && ! empty( $control->choices ) ) ? array_keys( $control->choices ) : array();
	return in_array( $value, $choices, true ) ? $value : $setting->default;
}

/* -------------------------------------------------------------- Registration */

/**
 * @param WP_Customize_Manager $wp_customize The manager.
 * @return void
 */
function suvantra_customize_register( $wp_customize ) {

	$languages = suvantra_languages();
	$defaults  = suvantra_design_defaults();

	$wp_customize->add_panel( 'suvantra', array(
		'title'       => 'Suvantra', // A name, not a word to translate.
		'priority'    => 30,
		'description' => __( 'The settings of this theme. The links in the header and footer come from the menus under Appearance → Menus.', 'suvantra' ),
	) );

	/* ------------------------------------------------------------- Brand */

	$wp_customize->add_section( 'suvantra_brand', array(
		'title'       => __( 'Brand', 'suvantra' ),
		'panel'       => 'suvantra',
		'priority'    => 5,
		'description' => __( 'Logo, site icon (the mark in the browser tab) and header image. WordPress otherwise spreads these three over two other sections; they sit together here because they are set together. They are the same settings, with the same cropper.', 'suvantra' ),
	) );

	/* WordPress registers these controls itself. Rather than putting our own
	   next to them, they are moved: same setting, same cropper, same hints. */
	foreach ( array( 'custom_logo', 'site_icon', 'header_image' ) as $inherited ) {
		$control = $wp_customize->get_control( $inherited );
		if ( $control ) {
			$control->section  = 'suvantra_brand';
			$control->priority = 10;
		}
	}

	$wp_customize->add_setting( 'suvantra_header_image_where', array(
		'default'           => 'all',
		'sanitize_callback' => 'suvantra_sanitize_choice',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_header_image_where', array(
		'label'       => __( 'Show header image', 'suvantra' ),
		'description' => __( 'Without an uploaded image nothing happens here — the pages then look exactly as they do now.', 'suvantra' ),
		'section'     => 'suvantra_brand',
		'type'        => 'radio',
		'choices'     => array(
			'all'  => __( 'On all pages', 'suvantra' ),
			'home' => __( 'On the front pages only', 'suvantra' ),
		),
	) );

	/* ----------------------------------------------------------- Product */

	$wp_customize->add_section( 'suvantra_product', array(
		'title'       => __( 'Product', 'suvantra' ),
		'panel'       => 'suvantra',
		'priority'    => 10,
		'description' => __( 'Applies to every product page in every language. The page content uses the placeholders %STORE_URL% and %DOWNLOAD_URL% for them.', 'suvantra' ),
	) );

	$wp_customize->add_setting( 'suvantra_store_url', array(
		'default'           => '',
		'sanitize_callback' => 'esc_url_raw',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_store_url', array(
		'label'       => __( 'Microsoft Store address', 'suvantra' ),
		'description' => __( 'Once the app is published. While the field is empty the button leads nowhere.', 'suvantra' ),
		'section'     => 'suvantra_product',
		'type'        => 'url',
		'input_attrs' => array( 'placeholder' => 'https://apps.microsoft.com/detail/...' ),
	) );

	$wp_customize->add_setting( 'suvantra_download_url', array(
		'default'           => '',
		'sanitize_callback' => 'esc_url_raw',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_download_url', array(
		'label'       => __( 'Direct download address', 'suvantra' ),
		'description' => __( 'The installer alongside the Store. Placeholder in the page content: %DOWNLOAD_URL%.', 'suvantra' ),
		'section'     => 'suvantra_product',
		'type'        => 'url',
		'input_attrs' => array( 'placeholder' => 'https://suvantra.eu/download/...' ),
	) );

	/* ------------------------------------------------------------ Header */

	$wp_customize->add_section( 'suvantra_header', array(
		'title'       => __( 'Header', 'suvantra' ),
		'panel'       => 'suvantra',
		'priority'    => 15,
		'description' => __( 'The logo is in the Brand section. The links come from the "Main navigation" menu of each language.', 'suvantra' ),
	) );

	$wp_customize->add_setting( 'suvantra_header_layout', array(
		'default'           => 'left',
		'sanitize_callback' => 'suvantra_sanitize_choice',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_header_layout', array(
		'label'       => __( 'Arrangement', 'suvantra' ),
		'description' => __( 'Where the brand, the navigation and the language switch sit. On narrow devices the bar wraps anyway — every arrangement looks the same there.', 'suvantra' ),
		'section'     => 'suvantra_header',
		'type'        => 'radio',
		'choices'     => array(
			'left'     => __( 'Brand left, navigation right', 'suvantra' ),
			'inline'   => __( 'Brand left, navigation next to it', 'suvantra' ),
			'centre'   => __( 'Brand centred, navigation below', 'suvantra' ),
			'mirrored' => __( 'Navigation left, brand right', 'suvantra' ),
		),
	) );

	$wp_customize->add_setting( 'suvantra_header_sticky', array(
		'default'           => true,
		'sanitize_callback' => 'suvantra_sanitize_checkbox',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_header_sticky', array(
		'label'       => __( 'Keep the header bar in view', 'suvantra' ),
		'description' => __( 'It stays at the top while scrolling, slightly translucent. Off means it scrolls away with the content. On long legal texts keeping it is kinder, because the way back stays within reach.', 'suvantra' ),
		'section'     => 'suvantra_header',
		'type'        => 'checkbox',
	) );

	$wp_customize->add_setting( 'suvantra_header_height', array(
		'default'           => $defaults['suvantra_header_height'],
		'sanitize_callback' => 'suvantra_sanitize_number',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_header_height', array(
		'label'       => __( 'Header bar height', 'suvantra' ),
		'description' => __( 'In pixels, 66 by default. Does not apply to the centred arrangement — that one follows its contents — nor to narrow devices.', 'suvantra' ),
		'section'     => 'suvantra_header',
		'type'        => 'number',
		'input_attrs' => array( 'min' => 52, 'max' => 104, 'step' => 2 ),
	) );

	$wp_customize->add_setting( 'suvantra_header_rule', array(
		'default'           => true,
		'sanitize_callback' => 'suvantra_sanitize_checkbox',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_header_rule', array(
		'label'       => __( 'Rule below the header bar', 'suvantra' ),
		'description' => __( 'Without it the sticky bar blurs into the content below as soon as both share a colour.', 'suvantra' ),
		'section'     => 'suvantra_header',
		'type'        => 'checkbox',
	) );

	$wp_customize->add_setting( 'suvantra_language_switcher', array(
		'default'           => true,
		'sanitize_callback' => 'suvantra_sanitize_checkbox',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_language_switcher', array(
		'label'       => __( 'Show the language switch', 'suvantra' ),
		'description' => __( 'It points at the counterpart of the current page, not merely at the other front page. From three languages on it turns into a list by itself.', 'suvantra' ),
		'section'     => 'suvantra_header',
		'type'        => 'checkbox',
	) );

	/* ------------------------------------------------------------ Footer */

	$wp_customize->add_section( 'suvantra_footer', array(
		'title'       => __( 'Footer', 'suvantra' ),
		'panel'       => 'suvantra',
		'priority'    => 20,
		'description' => __( 'Further links do not belong here but in the "Footer" menu of each language — there they can be sorted, nested and pointed outwards. Privacy and imprint are appended by the theme should they be missing from the menu.', 'suvantra' ),
	) );

	$wp_customize->add_setting( 'suvantra_footer_legal_auto', array(
		'default'           => false,
		'sanitize_callback' => 'suvantra_sanitize_checkbox',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_footer_legal_auto', array(
		'label'       => __( 'Append privacy and imprint automatically', 'suvantra' ),
		'description' => __( 'They are appended only when no menu item points at those addresses — the comparison is by address, not by label, so you may name them as you like in the menu. Switch this off and the footer shows nothing but the menu: convenient while arranging things, and your own responsibility afterwards, because an imprint has to stay reachable.', 'suvantra' ),
		'section'     => 'suvantra_footer',
		'type'        => 'checkbox',
	) );

	$wp_customize->add_setting( 'suvantra_footer_layout', array(
		'default'           => 'row',
		'sanitize_callback' => 'suvantra_sanitize_choice',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_footer_layout', array(
		'label'       => __( 'Layout', 'suvantra' ),
		'description' => __( 'Columns are worth it from roughly five links onwards. The top level menu items then become column headings and their children the links below.', 'suvantra' ),
		'section'     => 'suvantra_footer',
		'type'        => 'radio',
		'choices'     => array(
			'row'     => __( 'One row (few links)', 'suvantra' ),
			'columns' => __( 'Columns (menu with sub-items)', 'suvantra' ),
		),
	) );

	foreach ( $languages as $code => $language ) {
		$wp_customize->add_setting( 'suvantra_footer_copyright_' . $code, array(
			'default'           => '&copy; %YEAR% Suvantra',
			'sanitize_callback' => 'suvantra_sanitize_html',
			'transport'         => 'postMessage',
		) );
		$wp_customize->add_control( 'suvantra_footer_copyright_' . $code, array(
			/* translators: %s: language name, e.g. English. */
			'label'       => sprintf( __( 'Line on the left (%s)', 'suvantra' ), $language['name'] ),
			'description' => __( '%YEAR% is replaced by the current year.', 'suvantra' ),
			'section'     => 'suvantra_footer',
			'type'        => 'text',
		) );

		$wp_customize->add_setting( 'suvantra_footer_note_' . $code, array(
			'default'           => '',
			'sanitize_callback' => 'suvantra_sanitize_html',
			'transport'         => 'postMessage',
		) );
		$wp_customize->add_control( 'suvantra_footer_note_' . $code, array(
			/* translators: %s: language name, e.g. English. */
			'label'       => sprintf( __( 'Closing note (%s)', 'suvantra' ), $language['name'] ),
			'description' => __( 'A second, quieter line below. Leaving it empty hides it.', 'suvantra' ),
			'section'     => 'suvantra_footer',
			'type'        => 'textarea',
		) );
	}

	$wp_customize->add_setting( 'suvantra_footer_email', array(
		'default'           => 'support@suvantra.eu',
		'sanitize_callback' => 'suvantra_sanitize_email',
		'transport'         => 'postMessage',
	) );
	$wp_customize->add_control( 'suvantra_footer_email', array(
		'label'       => __( 'Contact address in the footer', 'suvantra' ),
		'description' => __( 'Emitted as a mailto link, with the characters obfuscated.', 'suvantra' ),
		'section'     => 'suvantra_footer',
		'type'        => 'email',
	) );

	$wp_customize->add_setting( 'suvantra_footer_email_show', array(
		'default'           => true,
		'sanitize_callback' => 'suvantra_sanitize_checkbox',
		'transport'         => 'postMessage',
	) );
	$wp_customize->add_control( 'suvantra_footer_email_show', array(
		'label'   => __( 'Show the contact address', 'suvantra' ),
		'section' => 'suvantra_footer',
		'type'    => 'checkbox',
	) );

	/* Swap the footer in the preview instead of reloading the whole page. The
	   return value is exactly what footer.php emits otherwise. */
	if ( isset( $wp_customize->selective_refresh ) ) {
		$footer_settings = array( 'suvantra_footer_email', 'suvantra_footer_email_show' );
		foreach ( array_keys( $languages ) as $code ) {
			$footer_settings[] = 'suvantra_footer_copyright_' . $code;
			$footer_settings[] = 'suvantra_footer_note_' . $code;
		}
		$wp_customize->selective_refresh->add_partial( 'suvantra_footer_partial', array(
			'selector'            => 'footer .wrap',
			'container_inclusive' => false,
			'settings'            => $footer_settings,
			'render_callback'     => 'suvantra_footer_content',
		) );
	}

	/* ------------------------------------------------------------ Design */

	$wp_customize->add_section( 'suvantra_design', array(
		'title'       => __( 'Design', 'suvantra' ),
		'panel'       => 'suvantra',
		'priority'    => 25,
		'description' => __( 'Font size, measure and dark mode. The colours are in the two sections below.', 'suvantra' ),
	) );

	$wp_customize->add_setting( 'suvantra_font_size', array(
		'default'           => $defaults['suvantra_font_size'],
		'sanitize_callback' => 'suvantra_sanitize_number',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_font_size', array(
		'label'       => __( 'Base font size', 'suvantra' ),
		'description' => __( 'In pixels, 17 by default. Headings and lead paragraphs are calculated from it; on narrow devices it stays one pixel smaller automatically.', 'suvantra' ),
		'section'     => 'suvantra_design',
		'type'        => 'number',
		'input_attrs' => array( 'min' => 15, 'max' => 20, 'step' => 1 ),
	) );

	$wp_customize->add_setting( 'suvantra_measure', array(
		'default'           => $defaults['suvantra_measure'],
		'sanitize_callback' => 'suvantra_sanitize_number',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_measure', array(
		'label'       => __( 'Maximum page width', 'suvantra' ),
		'description' => __( 'In pixels, 1180 by default. Affects header, footer and the sections — not the text column itself, which stays at 66 characters because longer lines read worse.', 'suvantra' ),
		'section'     => 'suvantra_design',
		'type'        => 'number',
		'input_attrs' => array( 'min' => 960, 'max' => 1440, 'step' => 20 ),
	) );

	$wp_customize->add_setting( 'suvantra_dark_mode', array(
		'default'           => true,
		'sanitize_callback' => 'suvantra_sanitize_checkbox',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_dark_mode', array(
		'label'       => __( 'Ship a dark mode', 'suvantra' ),
		'description' => __( 'The site follows the operating system setting. A program with seventeen colour schemes should not advertise on a site that knows only one — switching this off is meant for an emergency rather than for taste.', 'suvantra' ),
		'section'     => 'suvantra_design',
		'type'        => 'checkbox',
	) );

	/* ----------------------------------------------------------- Colours */

	$modes = array(
		'light' => array( __( 'Colours — light mode', 'suvantra' ), 30, __( 'The default. A value left unchanged emits nothing at all.', 'suvantra' ) ),
		'dark'  => array( __( 'Colours — dark mode', 'suvantra' ), 35, __( 'Applies when the operating system is set to dark. The same colours a shade lighter will not do — on a dark ground every colour reads stronger.', 'suvantra' ) ),
	);
	foreach ( $modes as $mode => $heading ) {
		$section = 'suvantra_colors_' . $mode;
		$wp_customize->add_section( $section, array(
			'title'       => $heading[0],
			'panel'       => 'suvantra',
			'priority'    => $heading[1],
			'description' => $heading[2] . ' ' . __( 'The text on coloured surfaces is not chosen but calculated from WCAG luminance — so the button label stays legible whatever colour sits beneath it.', 'suvantra' ),
		) );

		foreach ( suvantra_color_tokens() as $key => $token ) {
			$id = 'suvantra_color_' . $key . '_' . $mode;
			$wp_customize->add_setting( $id, array(
				'default'           => $token[ $mode ],
				'sanitize_callback' => 'sanitize_hex_color',
				'transport'         => 'refresh',
			) );
			$wp_customize->add_control( new WP_Customize_Color_Control( $wp_customize, $id, array(
				'label'       => $token['label'],
				'description' => $token['note'],
				'section'     => $section,
			) ) );
		}
	}

	/* ----------------------------------------------------- Head metadata */

	$wp_customize->add_section( 'suvantra_head', array(
		'title'       => __( 'Head metadata and share image', 'suvantra' ),
		'panel'       => 'suvantra',
		'priority'    => 40,
		'description' => __( 'canonical, hreflang and the Open Graph tags come from the theme, because only it recognises the language from the path. Title and description of individual pages live in the editor: the title as the page title, the description in the "Excerpt" field.', 'suvantra' ),
	) );

	$wp_customize->add_setting( 'suvantra_head_meta', array(
		'default'           => true,
		'sanitize_callback' => 'suvantra_sanitize_checkbox',
		'transport'         => 'refresh',
	) );
	$wp_customize->add_control( 'suvantra_head_meta', array(
		'label'       => __( 'Emit head metadata from the theme', 'suvantra' ),
		'description' => __( 'Switch off only if the job should go back to a plugin. While the box is ticked the matching Yoast output is suppressed so that nothing sits in the head twice.', 'suvantra' ),
		'section'     => 'suvantra_head',
		'type'        => 'checkbox',
	) );

	foreach ( $languages as $code => $language ) {
		$wp_customize->add_setting( 'suvantra_meta_description_' . $code, array(
			'default'           => '',
			'sanitize_callback' => 'sanitize_text_field',
			'transport'         => 'refresh',
		) );
		$wp_customize->add_control( 'suvantra_meta_description_' . $code, array(
			/* translators: %s: language name, e.g. English. */
			'label'       => sprintf( __( 'Default description (%s)', 'suvantra' ), $language['name'] ),
			'description' => __( 'Only for pages without an excerpt of their own. About 150 characters.', 'suvantra' ),
			'section'     => 'suvantra_head',
			'type'        => 'textarea',
		) );

		$wp_customize->add_setting( 'suvantra_share_image_' . $code, array(
			'default'           => 0,
			'sanitize_callback' => 'absint',
			'transport'         => 'refresh',
		) );
		$wp_customize->add_control( new WP_Customize_Media_Control( $wp_customize, 'suvantra_share_image_' . $code, array(
			/* translators: %s: language name, e.g. English. */
			'label'       => sprintf( __( 'Share image (%s)', 'suvantra' ), $language['name'] ),
			'description' => __( '1200×630. A fallback only — the page\'s featured image counts first, then the matching file in /assets/.', 'suvantra' ),
			'section'     => 'suvantra_head',
			'mime_type'   => 'image',
		) ) );
	}
}
add_action( 'customize_register', 'suvantra_customize_register' );

/*
 * No preview script of our own is needed: the partial registered above is
 * enough, WordPress loads customize-selective-refresh for it and fetches only
 * the footer while typing. None of that runs on the site itself — the promise
 * of loading nothing applies to visitors.
 */
